"use strict";
const DEFAULT_PASSWORD="free_member",PASSWORD_KEY="guild_countdown_password_hash",EXPIRES_KEY="guild_countdown_password_expires",AUTH_KEY="guild_countdown_authenticated",CHANGE_PASSWORD_AUTH="oafy7044";const $=id=>document.getElementById(id);
async function sha256(text){const data=new TextEncoder().encode(text),hash=await crypto.subtle.digest("SHA-256",data);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,"0")).join("")}async function getPasswordHash(){let h=localStorage.getItem(PASSWORD_KEY);if(!h){h=await sha256(DEFAULT_PASSWORD);localStorage.setItem(PASSWORD_KEY,h)}return h}function getExpiry(){return Number(localStorage.getItem(EXPIRES_KEY)||0)}function isPasswordExpired(){const e=getExpiry();return e>0&&Date.now()>=e}async function checkPassword(p){return p.length>0&&(await sha256(p))===await getPasswordHash()}
async function unlock(p){if(isPasswordExpired()){$("passwordError").textContent="パスワードの有効期限が切れています。管理者画面から更新してください。";return}if(await checkPassword(p)){sessionStorage.setItem(AUTH_KEY,"1");showApp()}else $("passwordError").textContent="パスワードが正しくありません。"}function showApp(){$("lockScreen").classList.add("hidden");$("adminScreen").classList.add("hidden");$("appContent").classList.remove("hidden");render()}function lock(){stop();manualPause=false;sessionStorage.removeItem(AUTH_KEY);$("appContent").classList.add("hidden");$("adminScreen").classList.add("hidden");$("lockScreen").classList.remove("hidden");$("passwordInput").value="";$("passwordInput").focus()}
function showAdmin(){$("lockScreen").classList.add("hidden");$("appContent").classList.add("hidden");$("adminScreen").classList.remove("hidden");$("changeAuth").classList.remove("hidden");$("adminPanel").classList.add("hidden");$("changeAuthPassword").value="";$("changeAuthError").textContent="";$("newPassword").value="";$("newPasswordConfirm").value="";$("adminError").textContent="";$("changeAuthPassword").focus()}function closeAdmin(){$("adminScreen").classList.add("hidden");if(sessionStorage.getItem(AUTH_KEY)==="1"&&!isPasswordExpired())$("appContent").classList.remove("hidden");else{$("lockScreen").classList.remove("hidden");$("passwordInput").focus()}}async function authorizeChange(){if($("changeAuthPassword").value!==CHANGE_PASSWORD_AUTH){$("changeAuthError").textContent="パスワード変更用パスワードが正しくありません。";$("changeAuthPassword").value="";return}$("changeAuth").classList.add("hidden");$("adminPanel").classList.remove("hidden");renderExpiry()}function renderExpiry(){const e=getExpiry();$("expiryStatus").textContent=e?new Date(e).toLocaleString("ja-JP")+" まで":"無期限"}async function changePassword(){const p=$("newPassword").value,c=$("newPasswordConfirm").value,days=Math.max(0,Number($("passwordDays").value)||0);if(p.length<4){$("adminError").textContent="新しいパスワードは4文字以上にしてください。";return}if(p!==c){$("adminError").textContent="新しいパスワードが一致しません。";return}localStorage.setItem(PASSWORD_KEY,await sha256(p));if(days)localStorage.setItem(EXPIRES_KEY,String(Date.now()+days*86400000));else localStorage.removeItem(EXPIRES_KEY);sessionStorage.removeItem(AUTH_KEY);$("adminError").textContent="パスワードを変更しました。新しいパスワードで再ログインしてください。";setTimeout(lock,900)}
const stages=[{id:"675",start:675,interval:4000},{id:"900",start:900,interval:3000},{id:"1350",start:1350,interval:2000}];let values=stages.map(s=>s.start),timers=[null,null,null],running=false,manualPause=false,lastTick=Date.now(),lastScheduleKey="";
function now(){return new Date()}function nextSchedule(){const d=now(),c=[new Date(d.getFullYear(),d.getMonth(),d.getDate(),21),new Date(d.getFullYear(),d.getMonth(),d.getDate(),22)];return c.find(x=>x>d)||new Date(d.getFullYear(),d.getMonth(),d.getDate()+1,21)}function scheduleLabel(){const d=now(),h=d.getHours(),m=d.getMinutes();if((h===21||h===22)&&m<60)return `本日の${String(h).padStart(2,"0")}:00 セッション`;const n=nextSchedule();return `次回 ${String(n.getHours()).padStart(2,"0")}:00 セッション`}
function render(){ $("session").textContent=scheduleLabel();stages.forEach((s,i)=>{$("count"+s.id).textContent=values[i];$("status"+s.id).textContent=running?`${s.interval/1000}秒ごとに1減算中`:(manualPause?"一時停止中":`${s.interval/1000}秒ごとに1減算`);$("count"+s.id).parentElement.classList.toggle("running",running)})}
function start(){if(running)return;running=true;manualPause=false;lastTick=Date.now();runLoop();render()}
function runLoop(){if(!running)return;const nowMs=Date.now(),elapsed=nowMs-lastTick;stages.forEach((s,i)=>{if(values[i]>0){const ticks=Math.floor(elapsed/s.interval);if(ticks>0){values[i]=Math.max(0,values[i]-ticks);lastTick+=ticks*s.interval}}});if(values.every(v=>v<=0)){running=false;render();return}render();requestAnimationFrame(runLoop)}
function stop(){running=false;render()}function reset(){stop();manualPause=false;values=stages.map(s=>s.start);lastTick=Date.now();render()}
function startScheduledSession(){reset();start()}
function checkSchedule(){const d=now(),h=d.getHours(),m=d.getMinutes(),s=d.getSeconds(),key=`${d.getFullYear()}-${d.getMonth()}-${d.getDate()}-${h}`;if(s===0&&m===0&&(h===21||h===22)&&lastScheduleKey!==key){lastScheduleKey=key;startScheduledSession()}render()}
$("startBtn").addEventListener("click",start);$("pauseBtn").addEventListener("click",()=>{if(running){stop();manualPause=true;render()}else start()});$("resetBtn").addEventListener("click",reset);$("passwordForm").addEventListener("submit",e=>{e.preventDefault();unlock($("passwordInput").value)});$("lockButton").addEventListener("click",lock);$("adminButton").addEventListener("click",showAdmin);$("adminAppButton").addEventListener("click",showAdmin);$("adminClose").addEventListener("click",closeAdmin);$("changeAuthButton").addEventListener("click",authorizeChange);$("changePasswordButton").addEventListener("click",changePassword);render();setInterval(checkSchedule,1000);getPasswordHash();if(sessionStorage.getItem(AUTH_KEY)==="1"&&!isPasswordExpired())showApp();if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));